import type { Product, PriceTier, Review, Variant } from "@/lib/types";

/* Deterministic pseudo-random so server and client always agree. */
function seeded(seed: string) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return () => {
    h += 0x6d2b79f5;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const round = (n: number) => Math.round(n * 100) / 100;

/** 12 weekly price points; deals only get a "lowest" label when the history supports it. */
function makeHistory(slug: string, price: number, compareAt?: number): number[] {
  const rnd = seeded(slug + "history");
  const pts: number[] = [];
  if (compareAt) {
    // Discounted items: history sits near the regular price, today is the genuine low.
    for (let i = 0; i < 11; i++) pts.push(round(compareAt * (1 - rnd() * 0.05)));
  } else {
    // Regular items: price moves around today's level — today is not a special low.
    for (let i = 0; i < 11; i++) pts.push(round(price * (0.97 + rnd() * 0.07)));
    pts[3 + Math.floor(rnd() * 6)] = round(price * 0.95);
  }
  pts.push(price);
  return pts;
}

function makeTiers(price: number, steps: [number, number][]): PriceTier[] {
  return steps.map(([min, pct]) => ({ min, price: round(price * (1 - pct)) }));
}

type Input = Omit<Product, "history" | "b2b" | "reviews" | "id" | "tint"> & {
  tint?: string;
  history?: number[];
  b2b?: Partial<Product["b2b"]> & { steps?: [number, number][] };
  reviews: Review[];
};

const TINTS: Record<string, string> = {
  "audio-tech": "#E8EBF2",
  "home-living": "#F0EBE3",
  kitchen: "#ECEFE4",
  fashion: "#ECEAEF",
  beauty: "#F3E9E5",
  office: "#E6EDEA",
  supplies: "#EFEAE1",
  safety: "#EEEFE2",
};

let counter = 1000;
function p(input: Input): Product {
  counter += 7;
  const { b2b = {}, ...rest } = input;
  const steps = b2b.steps ?? [
    [1, 0],
    [10, 0.06],
    [50, 0.12],
    [250, 0.19],
  ];
  const tiers = makeTiers(input.price, steps);
  return {
    ...rest,
    id: `ay-${counter}`,
    tint: input.tint ?? TINTS[input.category] ?? "#EEEFEA",
    history: input.history ?? makeHistory(input.slug, input.price, input.compareAt),
    b2b: {
      sku: b2b.sku ?? `AY-${input.slug.slice(0, 3).toUpperCase()}-${counter}`,
      unit: b2b.unit ?? "unit",
      caseQty: b2b.caseQty ?? 1,
      moq: b2b.moq ?? 1,
      tiers,
      leadDays: b2b.leadDays ?? input.delivery.max,
      rfq: b2b.rfq ?? true,
      taxExemptEligible: b2b.taxExemptEligible ?? true,
      contractPrice: b2b.contractPrice,
    },
  };
}

const v = (id: string, name: string, color: string, accent?: string): Variant => ({ id, name, color, accent });

export const products: Product[] = [
  /* ─── Audio & Tech ─────────────────────────────────────────── */
  p({
    slug: "aurel-anc-over-ear",
    name: "Aurel ANC Over-Ear Headphones",
    brand: "Northform",
    sellerId: "northform",
    category: "audio-tech",
    subcategory: "Headphones",
    kind: "headphones",
    variants: [v("chalk", "Chalk", "#E9E6DF", "#B9B4AA"), v("graphite", "Graphite", "#2A2D33", "#555A63"), v("moss", "Moss", "#7C8B6A", "#4E5A42")],
    price: 249,
    compareAt: 299,
    history: [299, 299, 289, 299, 299, 279, 299, 299, 289, 299, 299, 249],
    rating: 4.8,
    reviewCount: 3184,
    soldLastWeek: 1284,
    stock: 214,
    delivery: { min: 1, max: 2, express: 0 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Adaptive noise cancelling that measurably outperforms headphones twice the price, with 40 hours of battery and a fold-flat design.",
    highlights: ["-38 dB adaptive noise cancelling", "40 h battery · 10 min = 6 h", "Multipoint Bluetooth 5.4", "268 g, fold-flat"],
    specs: { Driver: "40 mm bio-cellulose", "Noise cancelling": "Adaptive, -38 dB", Battery: "40 h (ANC on)", Charging: "USB-C, fast charge", Weight: "268 g", Codecs: "AAC, LDAC, LC3", Warranty: "2 years" },
    brief: {
      pros: ["Class-leading cancellation on flights", "Comfortable for 6+ hour sessions", "Excellent call microphones"],
      cons: ["Case is larger than rivals", "No 3.5 mm cable in the box"],
      bestFor: "Frequent flyers and open-office focus",
    },
    tags: ["bestseller", "deal", "assured", "fast"],
    useCases: ["travel", "commute", "office", "focus"],
    keywords: ["headphones", "noise cancelling", "anc", "wireless", "bluetooth", "over-ear", "flight", "quiet"],
    b2b: { steps: [[1, 0], [10, 0.08], [50, 0.14], [200, 0.2]], leadDays: 3 },
    reviews: [
      { author: "Maya R.", rating: 5, title: "Quieter than my old flagship pair", body: "Flew SFO → JFK and heard nothing but my podcast. Clamping force is gentle enough to sleep in.", date: "2026-08-30", verified: true },
      { author: "Devon K.", role: "IT Lead, Harbor & Co.", rating: 5, title: "Rolled out to 60 people", body: "Volume pricing kicked in at 50 units and the multipoint pairing means no more helpdesk tickets about switching devices.", date: "2026-08-12", verified: true, business: true },
    ],
  }),
  p({
    slug: "aurel-buds-pro",
    name: "Aurel Buds Pro",
    brand: "Northform",
    sellerId: "northform",
    category: "audio-tech",
    subcategory: "Headphones",
    kind: "earbuds",
    variants: [v("chalk", "Chalk", "#EFEDE8", "#C9C5BC"), v("ink", "Ink", "#1C1E22", "#3C4048")],
    price: 169,
    rating: 4.6,
    reviewCount: 1422,
    soldLastWeek: 610,
    stock: 38,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Compact earbuds with the same adaptive ANC engine as the Aurel over-ears, in a pocketable case.",
    highlights: ["Adaptive ANC", "8 h + 30 h with case", "IPX5 sweat resistant", "Wireless charging"],
    specs: { Battery: "8 h / 38 h total", Resistance: "IPX5", Charging: "USB-C, Qi", Weight: "5.1 g per bud", Warranty: "2 years" },
    brief: { pros: ["Secure fit for running", "Strong ANC for the size"], cons: ["Touch controls are sensitive"], bestFor: "Gym and commuting" },
    tags: ["assured", "fast"],
    useCases: ["commute", "gym", "travel"],
    keywords: ["earbuds", "wireless", "anc", "noise cancelling", "running", "gym", "in-ear"],
    reviews: [
      { author: "Jonah P.", rating: 5, title: "Stay put on runs", body: "Three sizes of tips and the medium locked in. ANC on the subway is genuinely impressive.", date: "2026-09-02", verified: true },
      { author: "Leila S.", rating: 4, title: "Great, minor quibble", body: "Sound and battery are excellent. Tap controls trigger when adjusting fit.", date: "2026-08-21", verified: true },
    ],
  }),
  p({
    slug: "halo-speaker-mini",
    name: "Halo Speaker Mini",
    brand: "Northform",
    sellerId: "northform",
    category: "audio-tech",
    subcategory: "Speakers",
    kind: "speaker",
    variants: [v("sand", "Sand", "#D8CDBB", "#A99C86"), v("slate", "Slate", "#4A5059", "#2B2F35"), v("signal", "Signal", "#C8FF3D", "#8FBF1A")],
    price: 119,
    compareAt: 139,
    rating: 4.7,
    reviewCount: 2210,
    soldLastWeek: 840,
    stock: 520,
    delivery: { min: 1, max: 3 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A room-filling 360° speaker the size of a coffee cup, waterproof and good for 20 hours.",
    highlights: ["360° sound", "IP67 waterproof", "20 h battery", "Stereo pair"],
    specs: { Output: "20 W", Battery: "20 h", Resistance: "IP67", Weight: "540 g", Warranty: "2 years" },
    brief: { pros: ["Big bass for its size", "Survives the pool"], cons: ["No aux input"], bestFor: "Outdoors and kitchens" },
    tags: ["deal", "assured"],
    useCases: ["outdoor", "home", "gift"],
    keywords: ["speaker", "bluetooth", "portable", "waterproof", "party"],
    reviews: [
      { author: "Theo M.", rating: 5, title: "Punches above its weight", body: "Paired two for stereo on the patio. Sounds like a much bigger unit.", date: "2026-08-19", verified: true },
      { author: "Rina A.", rating: 4, title: "Great gift", body: "Bought three for the family. Signal colour is even better in person.", date: "2026-07-28", verified: true },
    ],
  }),
  p({
    slug: "kova-book-14-air",
    name: "Kova Book 14 Air",
    brand: "Kova",
    sellerId: "kova",
    category: "audio-tech",
    subcategory: "Laptops",
    kind: "laptop",
    variants: [v("silver", "Silver", "#D5D8DD", "#AEB3BA"), v("midnight", "Midnight", "#2B303A", "#1A1D23")],
    price: 1249,
    rating: 4.7,
    reviewCount: 986,
    soldLastWeek: 214,
    stock: 64,
    delivery: { min: 2, max: 3 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A 1.1 kg, fanless 14\" laptop with an all-day battery and a matte 2.8K display.",
    highlights: ["2.8K matte display", "18 h battery", "1.1 kg fanless", "16 GB / 512 GB"],
    specs: { Display: "14\" 2.8K, 120 Hz, matte", Memory: "16 GB", Storage: "512 GB SSD", Battery: "Up to 18 h", Weight: "1.1 kg", Ports: "2× USB-C, USB-A, HDMI", Warranty: "1 year (3 yr fleet)" },
    brief: { pros: ["Silent under load", "Excellent keyboard", "Real all-day battery"], cons: ["Only 2 USB-C ports"], bestFor: "Mobile professionals and fleet deployment" },
    tags: ["assured", "bulk"],
    useCases: ["office", "travel", "study"],
    keywords: ["laptop", "notebook", "computer", "ultrabook", "work"],
    b2b: { steps: [[1, 0], [5, 0.04], [25, 0.08], [100, 0.12]], leadDays: 4, contractPrice: 1099 },
    reviews: [
      { author: "Sam W.", rating: 5, title: "Silent and fast", body: "No fan noise at all in video calls. The matte screen is great outdoors.", date: "2026-09-05", verified: true },
      { author: "Priya N.", role: "Ops Manager, Kestrel Health", rating: 5, title: "Fleet program was painless", body: "Asset tags, pre-enrolled MDM and 3-year warranty on 40 units. Arrived in two days.", date: "2026-08-15", verified: true, business: true },
    ],
  }),
  p({
    slug: "kova-keys-low-profile",
    name: "Kova Keys Low-Profile",
    brand: "Kova",
    sellerId: "kova",
    category: "office",
    subcategory: "Peripherals",
    kind: "keyboard",
    variants: [v("porcelain", "Porcelain", "#EEEDE7", "#D4D3CC"), v("graphite", "Graphite", "#2E3238", "#474C54")],
    price: 139,
    rating: 4.6,
    reviewCount: 1830,
    soldLastWeek: 390,
    stock: 1200,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A quiet, low-profile mechanical keyboard that pairs with three devices.",
    highlights: ["Silent tactile switches", "3-device pairing", "3-month battery", "Mac & Windows layouts"],
    specs: { Switches: "Low-profile silent tactile", Connectivity: "Bluetooth, 2.4 GHz, USB-C", Battery: "3 months", Layouts: "US, UK, DE, FR", Warranty: "2 years" },
    brief: { pros: ["Office-quiet", "Great travel"], cons: ["No backlight on porcelain"], bestFor: "Shared workspaces" },
    tags: ["assured", "bulk", "fast"],
    useCases: ["office", "home"],
    keywords: ["keyboard", "mechanical", "wireless", "desk", "peripheral"],
    reviews: [
      { author: "Ari F.", rating: 5, title: "Finally, a quiet mechanical", body: "Nobody on my calls can hear me type anymore.", date: "2026-08-08", verified: true },
      { author: "Nadia E.", role: "Workplace, Loop Studio", rating: 4, title: "Great for hot desks", body: "Bought 30 for our hot-desking floor. Pairing is simple.", date: "2026-07-30", verified: true, business: true },
    ],
  }),
  p({
    slug: "kova-vista-27-4k",
    name: "Kova Vista 27\" 4K Monitor",
    brand: "Kova",
    sellerId: "kova",
    category: "audio-tech",
    subcategory: "Monitors",
    kind: "monitor",
    variants: [v("silver", "Silver", "#D9DBDF", "#A7ABB2")],
    price: 429,
    compareAt: 479,
    rating: 4.7,
    reviewCount: 1102,
    soldLastWeek: 260,
    stock: 180,
    delivery: { min: 2, max: 4 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Colour-accurate 27\" 4K with USB-C 90 W — one cable for power, display and peripherals.",
    highlights: ["4K IPS, 98% DCI-P3", "USB-C 90 W", "Height & swivel stand", "Built-in KVM"],
    specs: { Panel: "27\" IPS 4K", Color: "98% DCI-P3, ΔE<2", Connectivity: "USB-C 90 W, HDMI 2.1, DP 1.4", Stand: "Height, tilt, swivel, pivot", Warranty: "3 years" },
    brief: { pros: ["One-cable desk setup", "Factory calibrated"], cons: ["60 Hz only"], bestFor: "Designers and hybrid desks" },
    tags: ["deal", "bulk"],
    useCases: ["office", "design", "home"],
    keywords: ["monitor", "display", "screen", "4k", "usb-c"],
    reviews: [
      { author: "Colette B.", rating: 5, title: "Colours are spot-on", body: "Matched my calibrated reference out of the box.", date: "2026-08-26", verified: true },
      { author: "Omar T.", rating: 4, title: "Great hub monitor", body: "Laptop charges over the one cable. Wish it did 120 Hz.", date: "2026-08-02", verified: true },
    ],
  }),
  p({
    slug: "kova-one",
    name: "Kova One",
    brand: "Kova",
    sellerId: "kova",
    category: "audio-tech",
    subcategory: "Phones",
    kind: "phone",
    variants: [v("stone", "Stone", "#CFCBC2", "#A39E93"), v("ink", "Ink", "#1F2227", "#3A3F47"), v("blue", "Electric", "#5967FF", "#3F4BD6")],
    price: 699,
    rating: 4.5,
    reviewCount: 2640,
    soldLastWeek: 720,
    stock: 12,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A clean, unlocked phone with 5 years of updates and a 2-day battery.",
    highlights: ["5 years of updates", "2-day battery", "6.1\" OLED 120 Hz", "Unlocked, dual eSIM"],
    specs: { Display: "6.1\" OLED, 120 Hz", Storage: "256 GB", Battery: "4,700 mAh", Camera: "50 MP main, 12 MP ultra-wide", Warranty: "1 year" },
    brief: { pros: ["Clean software", "Battery lasts two days"], cons: ["Camera weaker in low light"], bestFor: "People who keep phones for years" },
    tags: ["new", "assured"],
    useCases: ["daily", "business"],
    keywords: ["phone", "smartphone", "mobile", "unlocked", "android"],
    reviews: [
      { author: "Hana L.", rating: 5, title: "Two days, genuinely", body: "Ended day two at 18%. The electric blue is stunning.", date: "2026-09-10", verified: true },
      { author: "Marco D.", rating: 4, title: "Solid everyday phone", body: "No bloat, fast updates. Night photos are just okay.", date: "2026-08-29", verified: true },
    ],
  }),

  /* ─── Home & Living ────────────────────────────────────────── */
  p({
    slug: "arc-table-lamp",
    name: "Arc Table Lamp",
    brand: "Atelier Mesa",
    sellerId: "atelier-mesa",
    category: "home-living",
    subcategory: "Lighting",
    kind: "lamp",
    variants: [v("travertine", "Travertine", "#E6DCCB", "#C9B99E"), v("black", "Black", "#23252A", "#43464D"), v("olive", "Olive", "#8C8F5A", "#686B3F")],
    price: 189,
    rating: 4.8,
    reviewCount: 742,
    soldLastWeek: 188,
    stock: 46,
    delivery: { min: 3, max: 5 },
    shipping: 0,
    returns: { days: 45, free: true },
    summary: "A sculptural table lamp with a hand-finished base and a dimmable warm LED.",
    highlights: ["Hand-finished base", "Dimmable 2700K LED", "Linen shade", "USB-C port in base"],
    specs: { Height: "46 cm", Shade: "Ø 32 cm linen", Light: "2700K, 800 lm, dimmable", Base: "Solid travertine or powder-coated steel", Warranty: "3 years" },
    brief: { pros: ["Beautiful warm light", "Heavy, stable base"], cons: ["Shade shows dust"], bestFor: "Bedside and reading corners" },
    tags: ["assured"],
    useCases: ["home", "bedroom", "gift"],
    keywords: ["lamp", "table lamp", "lighting", "light", "bedside"],
    reviews: [
      { author: "Iris W.", rating: 5, title: "Heirloom quality", body: "The travertine base is gorgeous and the dimmer is smooth all the way down.", date: "2026-08-11", verified: true },
      { author: "Ben C.", role: "Owner, Casa Lumen Hotel", rating: 5, title: "Ordered 48 for our rooms", body: "Seller offered a quote within the hour and split delivery over two dates.", date: "2026-07-19", verified: true, business: true },
    ],
  }),
  p({
    slug: "loom-lounge-chair",
    name: "Loom Lounge Chair",
    brand: "Atelier Mesa",
    sellerId: "atelier-mesa",
    category: "home-living",
    subcategory: "Seating",
    kind: "chair",
    variants: [v("oat", "Oat bouclé", "#E3DCCF", "#8A6A48"), v("rust", "Rust", "#B5613C", "#6E4A30"), v("moss", "Moss", "#6F7A55", "#4A3B2A")],
    price: 689,
    compareAt: 790,
    rating: 4.7,
    reviewCount: 318,
    soldLastWeek: 64,
    stock: 9,
    delivery: { min: 5, max: 8 },
    shipping: 49,
    returns: { days: 45, free: true },
    summary: "A low, generous lounge chair in solid oak with a removable, washable cover.",
    highlights: ["Solid FSC oak frame", "Removable washable cover", "Arrives assembled", "Seat height 40 cm"],
    specs: { Dimensions: "78 × 82 × 74 cm", "Seat height": "40 cm", Frame: "Solid FSC oak", Upholstery: "Bouclé, removable", Warranty: "5 years" },
    brief: { pros: ["Deep, supportive seat", "Cover is truly washable"], cons: ["Heavy to move"], bestFor: "Reading nooks and hotel lobbies" },
    tags: ["deal"],
    useCases: ["home", "hospitality"],
    keywords: ["chair", "armchair", "lounge", "seating", "furniture", "boucle"],
    b2b: { steps: [[1, 0], [4, 0.05], [12, 0.1], [40, 0.16]], leadDays: 14 },
    reviews: [
      { author: "Noor H.", rating: 5, title: "The comfiest chair I own", body: "Arrived fully assembled, white-glove delivery was on time to the hour.", date: "2026-08-04", verified: true },
      { author: "Felix G.", rating: 4, title: "Beautiful, heavy", body: "Solid build, takes two people to move. Worth it.", date: "2026-07-14", verified: true },
    ],
  }),
  p({
    slug: "stoneware-bud-vases",
    name: "Stoneware Bud Vase Trio",
    brand: "Kindred",
    sellerId: "kindred",
    category: "home-living",
    subcategory: "Decor",
    kind: "vase",
    variants: [v("bone", "Bone", "#EAE4D8", "#C9BFAD"), v("clay", "Clay", "#C98E6B", "#9E6A4C"), v("smoke", "Smoke", "#8F9398", "#6A6E73")],
    price: 54,
    rating: 4.9,
    reviewCount: 1206,
    soldLastWeek: 402,
    stock: 300,
    delivery: { min: 2, max: 4 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Three wheel-thrown bud vases in a speckled reactive glaze. Each set is unique.",
    highlights: ["Wheel-thrown by hand", "Lead-free glaze", "Set of three heights", "Gift-wrapped"],
    specs: { Heights: "10, 14, 18 cm", Material: "Stoneware", Care: "Hand wash", Origin: "Asheville, NC" },
    brief: { pros: ["Beautiful glaze variation", "Great gift packaging"], cons: ["Not dishwasher safe"], bestFor: "Gifting and shelves" },
    tags: ["bestseller", "eco"],
    useCases: ["home", "gift"],
    keywords: ["vase", "ceramic", "decor", "stoneware", "flowers", "gift"],
    reviews: [
      { author: "Clara J.", rating: 5, title: "Even better in person", body: "The speckled glaze is so subtle and lovely. Packaged beautifully.", date: "2026-09-01", verified: true },
      { author: "Tom V.", rating: 5, title: "Perfect housewarming gift", body: "Arrived in two days, gift-wrapped with a handwritten note.", date: "2026-08-18", verified: true },
    ],
  }),
  p({
    slug: "ember-soy-candle",
    name: "Ember Soy Candle — Fig & Cedar",
    brand: "Kindred",
    sellerId: "kindred",
    category: "home-living",
    subcategory: "Candles",
    kind: "candle",
    variants: [v("amber", "Amber glass", "#B7793C", "#F2E6D0"), v("smoke", "Smoke glass", "#55595F", "#EEE7DA")],
    price: 38,
    rating: 4.8,
    reviewCount: 2904,
    soldLastWeek: 930,
    stock: 740,
    delivery: { min: 1, max: 3 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A clean-burning soy candle with a cotton wick and a 60-hour burn.",
    highlights: ["60 h burn time", "Soy & coconut wax", "Cotton wick", "Refillable vessel"],
    specs: { Burn: "60 h", Wax: "Soy & coconut", Weight: "300 g", Notes: "Fig leaf, cedar, amber" },
    brief: { pros: ["Scent fills a room", "Even melt pool"], cons: ["Lid sold separately"], bestFor: "Gifting and evenings in" },
    tags: ["bestseller", "eco", "fast"],
    useCases: ["home", "gift", "hospitality"],
    keywords: ["candle", "scent", "soy", "home fragrance", "gift"],
    reviews: [
      { author: "Eve S.", rating: 5, title: "My third one", body: "Burns evenly to the bottom. The fig is subtle, not sweet.", date: "2026-09-06", verified: true },
      { author: "Lucas R.", rating: 4, title: "Lovely scent", body: "Wish the lid was included, otherwise perfect.", date: "2026-08-20", verified: true },
    ],
  }),
  p({
    slug: "olive-tree-terracotta",
    name: "Olive Tree in Terracotta",
    brand: "Kindred",
    sellerId: "kindred",
    category: "home-living",
    subcategory: "Plants",
    kind: "plant",
    variants: [v("terracotta", "Terracotta", "#C47A52", "#6F8455"), v("stone", "Stone pot", "#CFCABE", "#6F8455")],
    price: 79,
    rating: 4.6,
    reviewCount: 488,
    soldLastWeek: 120,
    stock: 70,
    delivery: { min: 2, max: 4 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A 70 cm indoor olive tree, nursery-grown and shipped in climate-controlled boxes.",
    highlights: ["70 cm tall", "Arrives potted", "30-day plant guarantee", "Care guide included"],
    specs: { Height: "~70 cm", Pot: "Ø 22 cm terracotta", Light: "Bright, direct", Water: "Every 10–14 days" },
    brief: { pros: ["Healthy on arrival", "Great packaging"], cons: ["Needs a sunny spot"], bestFor: "Bright living rooms" },
    tags: ["eco"],
    useCases: ["home", "gift", "office"],
    keywords: ["plant", "tree", "olive", "indoor plant", "greenery"],
    reviews: [
      { author: "Grace T.", rating: 5, title: "Arrived perfect", body: "Not a single leaf dropped. Clever box design.", date: "2026-08-24", verified: true },
      { author: "Omid Z.", rating: 4, title: "Healthy tree", body: "Smaller than expected but thriving after a month.", date: "2026-07-26", verified: true },
    ],
  }),

  /* ─── Kitchen & Coffee ─────────────────────────────────────── */
  p({
    slug: "pour-gooseneck-kettle",
    name: "Pour Gooseneck Kettle",
    brand: "Oro",
    sellerId: "oro",
    category: "kitchen",
    subcategory: "Kettles",
    kind: "kettle",
    variants: [v("matte-black", "Matte black", "#26282C", "#8C7A5B"), v("steel", "Brushed steel", "#C9CCD0", "#26282C"), v("chalk", "Chalk", "#EDEAE3", "#26282C")],
    price: 95,
    compareAt: 115,
    rating: 4.8,
    reviewCount: 1530,
    soldLastWeek: 360,
    stock: 260,
    delivery: { min: 1, max: 3 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A precise electric gooseneck with ±1° temperature hold and a 60-minute keep-warm.",
    highlights: ["±1°C precision", "Brew timer", "1.0 L", "60-min hold"],
    specs: { Capacity: "1.0 L", Power: "1200 W", Range: "40–100°C", Materials: "304 stainless steel", Warranty: "2 years" },
    brief: { pros: ["Perfect pour control", "Fast boil"], cons: ["Base cable is short"], bestFor: "Pour-over and tea" },
    tags: ["deal", "bestseller"],
    useCases: ["home", "cafe", "gift"],
    keywords: ["kettle", "gooseneck", "coffee", "tea", "pour over", "electric kettle"],
    reviews: [
      { author: "Yuki O.", rating: 5, title: "Pour-over game changer", body: "The flow rate is so controllable. Holds temperature exactly.", date: "2026-08-27", verified: true },
      { author: "Rosa P.", role: "Owner, Corner Bloom Café", rating: 5, title: "Six on our bar", body: "Case pricing via RFQ saved us 18%. Durable under café use.", date: "2026-07-22", verified: true, business: true },
    ],
  }),
  p({
    slug: "everyday-stoneware-mugs",
    name: "Everyday Stoneware Mugs, Set of 4",
    brand: "Kindred",
    sellerId: "kindred",
    category: "kitchen",
    subcategory: "Tableware",
    kind: "mug",
    variants: [v("bone", "Bone", "#EDE7DC", "#B8AE9C"), v("sage", "Sage", "#A7B39A", "#7D8A70"), v("ink", "Ink", "#2A2C31", "#4A4D54")],
    price: 42,
    rating: 4.8,
    reviewCount: 3302,
    soldLastWeek: 1040,
    stock: 1600,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Stackable 350 ml mugs with a comfortable handle and a satin glaze.",
    highlights: ["350 ml", "Stackable", "Dishwasher & microwave safe", "Chip-resistant rim"],
    specs: { Capacity: "350 ml", Material: "Stoneware", Care: "Dishwasher safe", Set: "4 mugs" },
    brief: { pros: ["Great weight in hand", "Stack neatly"], cons: ["Glaze shows tea stains"], bestFor: "Everyday use and offices" },
    tags: ["bestseller", "bulk", "fast"],
    useCases: ["home", "office", "cafe"],
    keywords: ["mug", "cup", "coffee", "tea", "tableware", "stoneware"],
    b2b: { unit: "set of 4", steps: [[1, 0], [12, 0.1], [48, 0.16], [120, 0.22]] },
    reviews: [
      { author: "Anya K.", rating: 5, title: "Perfect everyday mugs", body: "The handle fits four fingers. Stack beautifully in a small cupboard.", date: "2026-09-08", verified: true },
      { author: "Chris L.", role: "Office Manager, Northwind", rating: 5, title: "Restocked our kitchen", body: "Ordered 30 sets with our net-30 account. Zero breakages.", date: "2026-08-09", verified: true, business: true },
    ],
  }),
  p({
    slug: "guji-single-origin-1kg",
    name: "Ethiopia Guji Single Origin, 1 kg",
    brand: "Oro",
    sellerId: "oro",
    category: "kitchen",
    subcategory: "Coffee",
    kind: "coffeebag",
    variants: [v("whole", "Whole bean", "#E8D9BF", "#2A2C31"), v("espresso", "Espresso grind", "#D9C4A0", "#2A2C31")],
    price: 36,
    rating: 4.9,
    reviewCount: 2180,
    soldLastWeek: 1310,
    stock: 480,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 14, free: false },
    summary: "Washed Guji with notes of bergamot, peach and black tea. Roasted to order within 48 hours.",
    highlights: ["Roasted to order", "Direct trade", "Notes: bergamot, peach", "Subscribe & save 12%"],
    specs: { Origin: "Guji, Ethiopia", Process: "Washed", Altitude: "1,900–2,200 m", Roast: "Light-medium", Weight: "1 kg" },
    brief: { pros: ["Incredibly fresh", "Bright, clean cup"], cons: ["Light roast not for everyone"], bestFor: "Filter coffee lovers and cafés" },
    tags: ["bestseller", "eco", "bulk", "fast"],
    useCases: ["home", "cafe", "office"],
    keywords: ["coffee", "beans", "single origin", "ethiopia", "roast", "espresso"],
    b2b: { unit: "1 kg bag", caseQty: 6, steps: [[1, 0], [6, 0.1], [24, 0.18], [96, 0.26]], leadDays: 2 },
    reviews: [
      { author: "Dario F.", rating: 5, title: "Roast date was 2 days old", body: "Blooming like crazy. Peach note is very real.", date: "2026-09-11", verified: true },
      { author: "Kim N.", role: "Head Barista, Parlour", rating: 5, title: "Our house filter now", body: "Standing order every 2 weeks, never missed a delivery.", date: "2026-08-28", verified: true, business: true },
    ],
  }),

  /* ─── Fashion & Carry ──────────────────────────────────────── */
  p({
    slug: "stride-runner-2",
    name: "Stride Runner 2",
    brand: "Fieldwork",
    sellerId: "fieldwork",
    category: "fashion",
    subcategory: "Sneakers",
    kind: "sneaker",
    variants: [v("porcelain", "Porcelain", "#F1F0EA", "#C8FF3D"), v("ink", "Ink", "#1E2126", "#5967FF"), v("clay", "Clay", "#C9A58A", "#F1F0EA")],
    price: 148,
    rating: 4.7,
    reviewCount: 5120,
    soldLastWeek: 2240,
    stock: 880,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 60, free: true },
    summary: "A lightweight daily trainer with a recycled knit upper and a responsive foam midsole.",
    highlights: ["238 g (US 9)", "Recycled knit upper", "8 mm drop", "Free size exchanges"],
    specs: { Weight: "238 g", Drop: "8 mm", Upper: "Recycled knit", Midsole: "Supercritical EVA", Fit: "True to size (68%)" },
    brief: { pros: ["Light and bouncy", "Breathable in heat"], cons: ["Narrow toe box"], bestFor: "Daily runs and all-day wear" },
    tags: ["bestseller", "eco", "assured", "fast"],
    useCases: ["running", "daily", "travel"],
    keywords: ["sneaker", "shoe", "running shoe", "trainer", "sneakers", "shoes"],
    reviews: [
      { author: "Ivy C.", rating: 5, title: "Fits exactly like my old pair", body: "Ayiin Fit said 8.5 and it was spot on. Super light.", date: "2026-09-09", verified: true },
      { author: "Paul E.", rating: 4, title: "Great, a little narrow", body: "Love the ride, went half a size up for wide feet.", date: "2026-08-17", verified: true },
    ],
  }),
  p({
    slug: "transit-daypack-22",
    name: "Transit Daypack 22L",
    brand: "Fieldwork",
    sellerId: "fieldwork",
    category: "fashion",
    subcategory: "Bags",
    kind: "backpack",
    variants: [v("moss", "Moss", "#5D6B4F", "#C8FF3D"), v("ink", "Ink", "#23262B", "#C8FF3D"), v("sand", "Sand", "#CDBFA6", "#23262B")],
    price: 129,
    rating: 4.8,
    reviewCount: 2760,
    soldLastWeek: 690,
    stock: 410,
    delivery: { min: 1, max: 3 },
    shipping: 0,
    returns: { days: 60, free: true },
    summary: "A weatherproof commuter pack with a padded 16\" laptop sleeve and clamshell opening.",
    highlights: ["Weatherproof 500D", "16\" laptop sleeve", "Clamshell opening", "Lifetime warranty"],
    specs: { Capacity: "22 L", Weight: "0.95 kg", Material: "Recycled 500D nylon", Laptop: "Up to 16\"", Warranty: "Lifetime" },
    brief: { pros: ["Truly waterproof", "Excellent organisation"], cons: ["Hip belt not included"], bestFor: "Commuters and carry-on travel" },
    tags: ["assured", "eco", "bulk"],
    useCases: ["commute", "travel", "office"],
    keywords: ["backpack", "bag", "daypack", "laptop bag", "travel bag", "commuter"],
    b2b: { steps: [[1, 0], [25, 0.1], [100, 0.18], [500, 0.25]], leadDays: 10 },
    reviews: [
      { author: "Rae D.", rating: 5, title: "Survived a downpour", body: "Laptop bone dry after a 20-minute bike ride in heavy rain.", date: "2026-08-31", verified: true },
      { author: "Jules M.", role: "People Ops, Fathom", rating: 5, title: "Onboarding kit hero", body: "Custom-branded 120 packs for new hires. Proof approved in a day.", date: "2026-07-11", verified: true, business: true },
    ],
  }),
  p({
    slug: "meridian-automatic-38",
    name: "Meridian Automatic 38mm",
    brand: "Meridian",
    sellerId: "fieldwork",
    category: "fashion",
    subcategory: "Watches",
    kind: "watch",
    variants: [v("steel", "Steel / Porcelain", "#C9CCD1", "#F4F2EA"), v("gold", "Gold / Ink", "#C9A765", "#1C1E22")],
    price: 395,
    rating: 4.8,
    reviewCount: 612,
    soldLastWeek: 84,
    stock: 22,
    delivery: { min: 2, max: 3 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A 38 mm automatic with sapphire crystal, 100 m water resistance and a quick-release strap.",
    highlights: ["Swiss-made automatic", "Sapphire crystal", "100 m water resistant", "Quick-release strap"],
    specs: { Case: "38 mm, 316L steel", Movement: "Automatic, 38 h reserve", Crystal: "Sapphire, AR coated", Water: "100 m", Warranty: "3 years" },
    brief: { pros: ["Dressy yet sporty", "Crisp dial finishing"], cons: ["Strap is stiff at first"], bestFor: "Everyday elegance" },
    tags: ["new", "assured"],
    useCases: ["gift", "daily"],
    keywords: ["watch", "automatic", "wristwatch", "timepiece", "gift"],
    reviews: [
      { author: "Adrian Q.", rating: 5, title: "Punches way above its price", body: "Dial finishing is exceptional. Keeps +4 s/day.", date: "2026-09-03", verified: true },
      { author: "Sofia G.", rating: 5, title: "Perfect anniversary gift", body: "Engraving was free and it still arrived in 3 days.", date: "2026-08-13", verified: true },
    ],
  }),
  p({
    slug: "solstice-sunglasses",
    name: "Solstice Polarized Sunglasses",
    brand: "Fieldwork",
    sellerId: "fieldwork",
    category: "fashion",
    subcategory: "Eyewear",
    kind: "sunglasses",
    variants: [v("tortoise", "Tortoise", "#6B4A2E", "#2B3A2F"), v("black", "Black", "#1C1E22", "#23313D"), v("crystal", "Crystal", "#D8D4CC", "#4A5A3F")],
    price: 165,
    rating: 4.6,
    reviewCount: 840,
    soldLastWeek: 230,
    stock: 150,
    delivery: { min: 1, max: 3 },
    shipping: 0,
    returns: { days: 60, free: true },
    summary: "Hand-polished acetate frames with polarized mineral glass lenses.",
    highlights: ["Polarized glass lenses", "UV400", "Hand-polished acetate", "Free virtual try-on"],
    specs: { Lens: "Polarized mineral glass, UV400", Frame: "Bio-acetate", Fit: "Medium, 50-20-145" },
    brief: { pros: ["Crystal-clear lenses", "Sturdy hinges"], cons: ["Heavier than plastic"], bestFor: "Driving and bright days" },
    tags: ["eco"],
    useCases: ["travel", "outdoor", "gift"],
    keywords: ["sunglasses", "glasses", "eyewear", "polarized", "shades"],
    reviews: [
      { author: "Leo B.", rating: 5, title: "Glass lenses make a difference", body: "So much sharper than my old pair. Case is lovely too.", date: "2026-08-22", verified: true },
      { author: "Mina Y.", rating: 4, title: "Great quality", body: "A bit heavy on long days but beautiful frames.", date: "2026-07-31", verified: true },
    ],
  }),
  p({
    slug: "trail-bottle-750",
    name: "Trail Insulated Bottle 750 ml",
    brand: "Fieldwork",
    sellerId: "fieldwork",
    category: "fashion",
    subcategory: "Bottles",
    kind: "bottle",
    variants: [v("signal", "Signal", "#C8FF3D", "#1C1E22"), v("blue", "Electric", "#5967FF", "#1C1E22"), v("chalk", "Chalk", "#ECEAE3", "#1C1E22"), v("ink", "Ink", "#23262B", "#C8FF3D")],
    price: 34,
    rating: 4.8,
    reviewCount: 4410,
    soldLastWeek: 1980,
    stock: 3200,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 60, free: true },
    summary: "Double-wall steel bottle that keeps drinks cold for 24 hours — and takes custom logos.",
    highlights: ["Cold 24 h / hot 12 h", "Leak-proof lid", "Dishwasher safe", "Custom logo from 50 units"],
    specs: { Capacity: "750 ml", Material: "18/8 stainless steel", Weight: "360 g", Branding: "Laser or print, from 50 units" },
    brief: { pros: ["Genuinely leak-proof", "Colours are vivid"], cons: ["Doesn't fit small cup holders"], bestFor: "Daily hydration and team merch" },
    tags: ["bestseller", "eco", "bulk", "fast"],
    useCases: ["gym", "outdoor", "office", "gift"],
    keywords: ["bottle", "water bottle", "insulated", "flask", "merch"],
    b2b: { steps: [[1, 0], [50, 0.15], [250, 0.24], [1000, 0.32]], leadDays: 12, moq: 1 },
    reviews: [
      { author: "Zoe A.", rating: 5, title: "Ice still there next morning", body: "Left it in a hot car, still ice cold. The signal colour is great.", date: "2026-09-12", verified: true },
      { author: "Ethan W.", role: "Events, Linea", rating: 5, title: "Conference merch done right", body: "500 laser-engraved bottles. Proof in 24h, delivered in 11 days.", date: "2026-08-06", verified: true, business: true },
    ],
  }),

  /* ─── Beauty & Wellness ────────────────────────────────────── */
  p({
    slug: "clarity-niacinamide-serum",
    name: "Clarity Serum — 10% Niacinamide",
    brand: "Solace Labs",
    sellerId: "solace",
    category: "beauty",
    subcategory: "Skincare",
    kind: "serum",
    variants: [v("30", "30 ml", "#E9D8CE", "#2A2C31"), v("60", "60 ml", "#E9D8CE", "#2A2C31")],
    price: 28,
    rating: 4.7,
    reviewCount: 6120,
    soldLastWeek: 2710,
    stock: 2100,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A lightweight serum that visibly refines pores and evens tone in 4 weeks.",
    highlights: ["10% niacinamide + 1% zinc", "Fragrance-free", "Derm tested", "Opened returns accepted"],
    specs: { Actives: "10% niacinamide, 1% zinc PCA", Size: "30 ml", Skin: "All, incl. sensitive", "Fragrance-free": "Yes" },
    brief: { pros: ["Visible results in weeks", "No pilling under SPF"], cons: ["Slightly tacky for 1 min"], bestFor: "Oily and combination skin" },
    tags: ["bestseller", "fast"],
    useCases: ["daily", "gift"],
    keywords: ["serum", "skincare", "niacinamide", "face", "beauty", "pores"],
    reviews: [
      { author: "Lena F.", rating: 5, title: "Pores visibly smaller", body: "Four weeks in and my T-zone is so much calmer.", date: "2026-09-07", verified: true },
      { author: "Aisha M.", rating: 4, title: "Works well", body: "Great under makeup, slightly sticky right after applying.", date: "2026-08-25", verified: true },
    ],
  }),
  p({
    slug: "night-recovery-oil",
    name: "Night Recovery Facial Oil",
    brand: "Solace Labs",
    sellerId: "solace",
    category: "beauty",
    subcategory: "Skincare",
    kind: "serum",
    tint: "#EFE6DA",
    variants: [v("30", "30 ml", "#C98A3C", "#F1E9DD")],
    price: 46,
    rating: 4.8,
    reviewCount: 1480,
    soldLastWeek: 520,
    stock: 640,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Squalane and bakuchiol in a fast-absorbing oil for overnight repair.",
    highlights: ["Squalane + bakuchiol", "Non-comedogenic", "Absorbs in 60 s", "Recyclable glass"],
    specs: { Actives: "Squalane, 1% bakuchiol", Size: "30 ml", Skin: "Dry, normal" },
    brief: { pros: ["Morning glow", "Not greasy"], cons: ["Subtle herbal scent"], bestFor: "Dry and mature skin" },
    tags: ["new", "eco"],
    useCases: ["daily", "gift"],
    keywords: ["oil", "face oil", "skincare", "night", "beauty"],
    reviews: [
      { author: "Beatrice H.", rating: 5, title: "Woke up glowing", body: "Absorbs quickly and no breakouts.", date: "2026-09-04", verified: true },
      { author: "Nina P.", rating: 5, title: "Worth it", body: "A few drops last all night. Lovely bottle.", date: "2026-08-14", verified: true },
    ],
  }),

  /* ─── Office & Workspace ───────────────────────────────────── */
  p({
    slug: "ergo-task-chair-pro",
    name: "Ergo Task Chair Pro",
    brand: "Brightline",
    sellerId: "brightline",
    category: "office",
    subcategory: "Seating",
    kind: "taskchair",
    variants: [v("graphite", "Graphite", "#2B2E34", "#5967FF"), v("fog", "Fog", "#C9CCC8", "#2B2E34")],
    price: 549,
    compareAt: 649,
    rating: 4.7,
    reviewCount: 2860,
    soldLastWeek: 410,
    stock: 340,
    delivery: { min: 2, max: 4 },
    shipping: 0,
    returns: { days: 60, free: true },
    summary: "BIFMA-certified ergonomic chair with adaptive lumbar support and 4D arms.",
    highlights: ["Adaptive lumbar", "4D arms", "BIFMA certified", "12-year warranty"],
    specs: { Certification: "BIFMA X5.1", "Weight capacity": "150 kg", Adjustments: "Seat depth, 4D arms, tilt lock", Warranty: "12 years" },
    brief: { pros: ["All-day comfort", "Easy to tune"], cons: ["Assembly takes 20 min"], bestFor: "Full-time desk work, team fit-outs" },
    tags: ["deal", "bulk", "assured"],
    useCases: ["office", "home office"],
    keywords: ["chair", "office chair", "ergonomic", "desk chair", "task chair", "seating"],
    b2b: { steps: [[1, 0], [10, 0.08], [50, 0.15], [150, 0.22]], leadDays: 6, contractPrice: 469 },
    reviews: [
      { author: "Hugo S.", rating: 5, title: "Back pain gone", body: "The lumbar actually follows you when you lean back.", date: "2026-08-23", verified: true },
      { author: "Tara J.", role: "Facilities, Meridian Labs", rating: 5, title: "Outfitted 120 desks", body: "Approval flow and staggered delivery across 3 floors worked perfectly.", date: "2026-07-18", verified: true, business: true },
    ],
  }),
  p({
    slug: "premium-copy-paper-a4",
    name: "Premium Copy Paper A4, 80 gsm — 5 Reams",
    brand: "Brightline",
    sellerId: "brightline",
    category: "office",
    subcategory: "Paper",
    kind: "paper",
    variants: [v("white", "Bright white", "#F7F7F2", "#5967FF")],
    price: 32.99,
    rating: 4.8,
    reviewCount: 9210,
    soldLastWeek: 6400,
    stock: 24000,
    delivery: { min: 1, max: 1 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Jam-free, FSC-certified 80 gsm copy paper. 2,500 sheets per case.",
    highlights: ["FSC certified", "99.98% jam-free", "2,500 sheets", "Next-day delivery"],
    specs: { Size: "A4 (210 × 297 mm)", Weight: "80 gsm", Brightness: "CIE 161", Sheets: "5 × 500", Certification: "FSC, EU Ecolabel" },
    brief: { pros: ["Never jams", "Bright and crisp"], cons: ["Heavy boxes"], bestFor: "Every office printer" },
    tags: ["bestseller", "bulk", "eco", "fast"],
    useCases: ["office", "school"],
    keywords: ["paper", "copy paper", "printer paper", "a4", "reams", "office supplies"],
    b2b: { unit: "case (5 reams)", caseQty: 1, moq: 1, steps: [[1, 0], [10, 0.1], [40, 0.18], [120, 0.25]], leadDays: 1, contractPrice: 27.5 },
    reviews: [
      { author: "Walt R.", role: "Office Manager, Crane & Bell", rating: 5, title: "Auto-reorder saves us", body: "Scheduled 12 cases monthly. Never think about it anymore.", date: "2026-09-01", verified: true, business: true },
      { author: "Gina D.", rating: 5, title: "Great paper", body: "Bright, crisp, next-day as promised.", date: "2026-08-10", verified: true },
    ],
  }),
  p({
    slug: "scanline-barcode-scanner",
    name: "Scanline 2D Wireless Barcode Scanner",
    brand: "Brightline",
    sellerId: "brightline",
    category: "office",
    subcategory: "Scanning",
    kind: "scanner",
    variants: [v("ink", "Ink", "#24272C", "#C8FF3D")],
    price: 89,
    rating: 4.6,
    reviewCount: 1270,
    soldLastWeek: 380,
    stock: 900,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A rugged 2D scanner that reads damaged labels and screens, with a 2-metre drop rating.",
    highlights: ["Reads 1D/2D & screens", "2 m drop rated", "100 m range", "Plug & play"],
    specs: { Symbologies: "1D, QR, DataMatrix, PDF417", Range: "100 m wireless", Battery: "2,600 mAh", Rating: "IP54, 2 m drop" },
    brief: { pros: ["Fast on damaged codes", "Charging cradle included"], cons: ["Beep is loud"], bestFor: "Warehouses and retail counters" },
    tags: ["bulk", "fast"],
    useCases: ["warehouse", "retail"],
    keywords: ["scanner", "barcode", "qr", "warehouse", "inventory", "pos"],
    reviews: [
      { author: "Luis O.", role: "Warehouse Lead, Stackd", rating: 5, title: "Survives the floor", body: "Dropped daily on concrete, still going. Reads scuffed labels instantly.", date: "2026-08-19", verified: true, business: true },
      { author: "Kate I.", rating: 4, title: "Easy setup", body: "Plugged in, worked. Beep volume took some finding.", date: "2026-07-24", verified: true },
    ],
  }),

  /* ─── Packaging & Supplies ─────────────────────────────────── */
  p({
    slug: "double-wall-cartons-12x10x8",
    name: "Double-Wall Shipping Cartons 12×10×8\" — 25 pack",
    brand: "Parcel & Crate",
    sellerId: "parcel",
    category: "supplies",
    subcategory: "Shipping cartons",
    kind: "carton",
    variants: [v("kraft", "Kraft", "#C99B64", "#8C6538"), v("white", "White", "#EFEAE0", "#B9AE98")],
    price: 48,
    rating: 4.8,
    reviewCount: 3410,
    soldLastWeek: 5200,
    stock: 18000,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "ECT-32 double-wall cartons rated to 30 kg, stocked in Reno and Allentown.",
    highlights: ["ECT-32 double wall", "Holds 30 kg", "FSC certified", "Ships from 2 warehouses"],
    specs: { "Inner size": "12 × 10 × 8 in", Rating: "ECT-32, 200#", Pack: "25 cartons", Material: "FSC recycled kraft" },
    brief: { pros: ["Sturdy corners", "Flat-packed neatly"], cons: ["Tape not included"], bestFor: "E-commerce fulfilment" },
    tags: ["bestseller", "bulk", "eco", "fast"],
    useCases: ["warehouse", "shipping"],
    keywords: ["box", "boxes", "carton", "cartons", "shipping box", "packaging", "moving"],
    b2b: { unit: "pack of 25", caseQty: 1, moq: 1, steps: [[1, 0], [10, 0.12], [40, 0.22], [160, 0.3]], leadDays: 2 },
    reviews: [
      { author: "Bea N.", role: "Founder, Pantry Goods", rating: 5, title: "Our default box", body: "Consistent quality every shipment. Pallet pricing is excellent.", date: "2026-09-05", verified: true, business: true },
      { author: "Mo K.", rating: 5, title: "Great for moving", body: "Held heavy books without bulging.", date: "2026-08-03", verified: true },
    ],
  }),
  p({
    slug: "kraft-mailer-boxes",
    name: "Kraft Mailer Boxes 9×6×3\" — 50 pack",
    brand: "Parcel & Crate",
    sellerId: "parcel",
    category: "supplies",
    subcategory: "Mailers",
    kind: "carton",
    tint: "#EDE6DA",
    variants: [v("kraft", "Kraft", "#B98A55", "#EFE7D8"), v("ink", "Ink", "#2A2C31", "#C8FF3D")],
    price: 39,
    rating: 4.7,
    reviewCount: 1890,
    soldLastWeek: 2100,
    stock: 9600,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Tuck-front mailers that assemble without tape — custom print available from 500.",
    highlights: ["Tape-free assembly", "Custom print from 500", "Recyclable", "Crush resistant"],
    specs: { "Inner size": "9 × 6 × 3 in", Board: "E-flute", Pack: "50 mailers", Printing: "1–4 colours, from 500 units" },
    brief: { pros: ["Premium unboxing", "Fast assembly"], cons: ["Ink colour scuffs"], bestFor: "DTC brands" },
    tags: ["bulk", "eco"],
    useCases: ["shipping", "retail"],
    keywords: ["mailer", "box", "boxes", "packaging", "shipping", "subscription box"],
    b2b: { unit: "pack of 50", steps: [[1, 0], [10, 0.1], [50, 0.2], [200, 0.28]], leadDays: 2 },
    reviews: [
      { author: "June P.", role: "Ops, Softline", rating: 5, title: "Customers love them", body: "Custom print run turned around in 9 days.", date: "2026-08-21", verified: true, business: true },
      { author: "Ray T.", rating: 4, title: "Great mailers", body: "Sturdy, no tape needed. Ink version scuffs a little.", date: "2026-07-27", verified: true },
    ],
  }),

  /* ─── Safety & Facility ────────────────────────────────────── */
  p({
    slug: "nitrile-gloves-4mil",
    name: "Nitrile Exam Gloves 4 mil — Box of 100",
    brand: "Guardline",
    sellerId: "guardline",
    category: "safety",
    subcategory: "Gloves",
    kind: "gloves",
    variants: [v("blue", "Cobalt", "#5967FF", "#EDEFF5"), v("black", "Black", "#1F2226", "#EDEFF5")],
    price: 14.5,
    rating: 4.8,
    reviewCount: 7840,
    soldLastWeek: 12400,
    stock: 64000,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Powder-free, latex-free nitrile gloves certified for food handling and medical exam.",
    highlights: ["EN 374 & ASTM D6319", "Powder & latex free", "Textured fingertips", "Sizes XS–XXL"],
    specs: { Thickness: "4 mil", Certification: "EN 374, ASTM D6319, FDA 510(k)", Count: "100 per box, 10 boxes per case", Sizes: "XS–XXL" },
    brief: { pros: ["Doesn't tear when donning", "Good grip when wet"], cons: ["Runs slightly small"], bestFor: "Kitchens, clinics, labs" },
    tags: ["bestseller", "bulk", "fast"],
    useCases: ["kitchen", "clinic", "cleaning", "warehouse"],
    keywords: ["gloves", "nitrile", "ppe", "disposable gloves", "safety", "exam gloves"],
    b2b: { unit: "box of 100", caseQty: 10, moq: 1, steps: [[1, 0], [10, 0.12], [50, 0.22], [200, 0.32]], leadDays: 1, contractPrice: 10.9 },
    reviews: [
      { author: "Dr. Ana V.", role: "Clinic Director, Parkside", rating: 5, title: "Consistent quality", body: "We go through 40 cases a month. Standing order has never slipped.", date: "2026-09-08", verified: true, business: true },
      { author: "Jamal B.", rating: 4, title: "Good gloves", body: "Size up if between sizes.", date: "2026-08-12", verified: true },
    ],
  }),
  p({
    slug: "vented-safety-helmet",
    name: "Vented Safety Helmet, Type II",
    brand: "Guardline",
    sellerId: "guardline",
    category: "safety",
    subcategory: "Head protection",
    kind: "helmet",
    variants: [v("white", "White", "#F2F1EC", "#1F2226"), v("signal", "Signal", "#C8FF3D", "#1F2226"), v("blue", "Blue", "#5967FF", "#1F2226")],
    price: 29,
    rating: 4.7,
    reviewCount: 2210,
    soldLastWeek: 1900,
    stock: 8800,
    delivery: { min: 1, max: 3 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "A lightweight Type II helmet with ratchet suspension and adjustable venting.",
    highlights: ["ANSI Z89.1 Type II", "6-point ratchet", "Adjustable vents", "Custom logos from 25"],
    specs: { Standard: "ANSI/ISEA Z89.1 Type II Class C", Weight: "410 g", Suspension: "6-point ratchet", Branding: "Pad print from 25" },
    brief: { pros: ["Light and cool", "Comfortable suspension"], cons: ["Vents not for electrical work"], bestFor: "Construction and site visits" },
    tags: ["bulk"],
    useCases: ["construction", "warehouse"],
    keywords: ["helmet", "hard hat", "hardhat", "ppe", "safety", "construction"],
    b2b: { steps: [[1, 0], [25, 0.1], [100, 0.18], [500, 0.26]], leadDays: 3 },
    reviews: [
      { author: "Rick H.", role: "Site Manager, Ironbridge", rating: 5, title: "Crew actually wears them", body: "Light enough that nobody complains. Logo print looks sharp.", date: "2026-08-15", verified: true, business: true },
      { author: "Sven L.", rating: 4, title: "Comfortable", body: "Ratchet is smooth. Solid value.", date: "2026-07-29", verified: true },
    ],
  }),
  p({
    slug: "eco-surface-cleaner",
    name: "Eco Surface Cleaner — 4 × 750 ml",
    brand: "Guardline",
    sellerId: "guardline",
    category: "safety",
    subcategory: "Cleaning",
    kind: "spray",
    variants: [v("citrus", "Citrus", "#F0EFE6", "#C8FF3D"), v("unscented", "Unscented", "#F0EFE6", "#9CA3AF")],
    price: 24,
    rating: 4.6,
    reviewCount: 1640,
    soldLastWeek: 3100,
    stock: 12000,
    delivery: { min: 1, max: 2 },
    shipping: 0,
    returns: { days: 30, free: true },
    summary: "Plant-based multi-surface cleaner, EPA Safer Choice certified, in refillable bottles.",
    highlights: ["EPA Safer Choice", "Refillable bottles", "Streak-free", "Concentrate refills"],
    specs: { Volume: "4 × 750 ml", Certification: "EPA Safer Choice", Surfaces: "Glass, steel, stone, laminate" },
    brief: { pros: ["No harsh smell", "Streak-free on glass"], cons: ["Trigger can stiffen"], bestFor: "Offices, cafés, homes" },
    tags: ["eco", "bulk", "fast"],
    useCases: ["cleaning", "office", "cafe", "home"],
    keywords: ["cleaner", "cleaning", "spray", "janitorial", "surface cleaner", "eco"],
    b2b: { unit: "pack of 4", steps: [[1, 0], [12, 0.1], [48, 0.18], [200, 0.25]], leadDays: 2 },
    reviews: [
      { author: "Petra W.", role: "Facilities, Loom Studios", rating: 5, title: "Staff prefer it", body: "No more chemical smell in the office. Refills cut our plastic by 80%.", date: "2026-08-30", verified: true, business: true },
      { author: "Owen F.", rating: 4, title: "Works great", body: "Streak-free on our glass doors.", date: "2026-08-07", verified: true },
    ],
  }),
];

export const productBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const productsByCategory = (slug: string) => products.filter((p) => p.category === slug);
export const productById = (id: string) => products.find((p) => p.id === id);
