import type { Seller } from "@/lib/types";

export const sellers: Seller[] = [
  {
    id: "northform",
    name: "Northform Audio",
    initials: "NF",
    tagline: "Acoustic engineering studio, Portland",
    location: "Portland, OR",
    since: 2019,
    rating: 4.9,
    reviews: 18420,
    onTime: 99.1,
    responseHours: 1.2,
    returnRate: 1.8,
    orders: 212000,
    verified: true,
    business: true,
    netTerms: "Net 30",
    certifications: ["Brand owner", "Authorized warranty"],
    color: "#5967FF",
  },
  {
    id: "kova",
    name: "Kova Electronics",
    initials: "KV",
    tagline: "Official Kova brand store",
    location: "San Jose, CA",
    since: 2017,
    rating: 4.8,
    reviews: 51230,
    onTime: 98.6,
    responseHours: 2.1,
    returnRate: 2.4,
    orders: 640000,
    verified: true,
    business: true,
    netTerms: "Net 30 / Net 60",
    certifications: ["Brand owner", "Fleet program", "ISO 9001"],
    color: "#0A0B0D",
  },
  {
    id: "atelier-mesa",
    name: "Atelier Mesa",
    initials: "AM",
    tagline: "Independent furniture & lighting studio",
    location: "Mexico City, MX",
    since: 2020,
    rating: 4.8,
    reviews: 3120,
    onTime: 97.4,
    responseHours: 3.5,
    returnRate: 2.9,
    orders: 18400,
    verified: true,
    business: true,
    netTerms: "Net 30",
    certifications: ["FSC wood", "Maker verified"],
    color: "#C07A45",
  },
  {
    id: "kindred",
    name: "Kindred Home Co.",
    initials: "KH",
    tagline: "Ceramics & home goods, small-batch",
    location: "Asheville, NC",
    since: 2018,
    rating: 4.7,
    reviews: 9840,
    onTime: 98.2,
    responseHours: 2.8,
    returnRate: 3.1,
    orders: 76000,
    verified: true,
    business: false,
    certifications: ["Maker verified", "Lead-free glazes"],
    color: "#56662B",
  },
  {
    id: "solace",
    name: "Solace Labs",
    initials: "SL",
    tagline: "Dermatologist-formulated skincare",
    location: "Brooklyn, NY",
    since: 2021,
    rating: 4.8,
    reviews: 22100,
    onTime: 99.3,
    responseHours: 1.6,
    returnRate: 1.2,
    orders: 154000,
    verified: true,
    business: false,
    certifications: ["Cruelty-free", "Derm tested"],
    color: "#D06A5B",
  },
  {
    id: "fieldwork",
    name: "Fieldwork Supply",
    initials: "FW",
    tagline: "Carry goods built for daily miles",
    location: "Denver, CO",
    since: 2016,
    rating: 4.8,
    reviews: 14300,
    onTime: 98.9,
    responseHours: 2.0,
    returnRate: 2.2,
    orders: 131000,
    verified: true,
    business: true,
    netTerms: "Net 30",
    certifications: ["Bluesign fabrics", "Custom branding"],
    color: "#2F8F7A",
  },
  {
    id: "oro",
    name: "Oro Coffee Roasters",
    initials: "OR",
    tagline: "Direct-trade roastery & brew gear",
    location: "Oakland, CA",
    since: 2015,
    rating: 4.9,
    reviews: 8700,
    onTime: 99.4,
    responseHours: 1.1,
    returnRate: 0.9,
    orders: 98000,
    verified: true,
    business: true,
    netTerms: "Net 15",
    certifications: ["Direct trade", "Wholesale program"],
    color: "#8A5A2B",
  },
  {
    id: "brightline",
    name: "Brightline Office",
    initials: "BO",
    tagline: "Workspace supply for 12,000+ companies",
    location: "Columbus, OH",
    since: 2014,
    rating: 4.7,
    reviews: 40200,
    onTime: 98.8,
    responseHours: 0.8,
    returnRate: 1.5,
    orders: 910000,
    verified: true,
    business: true,
    netTerms: "Net 30 / Net 60",
    certifications: ["BIFMA partner", "Punch-out catalog", "SOC 2"],
    color: "#2F8F7A",
  },
  {
    id: "parcel",
    name: "Parcel & Crate",
    initials: "PC",
    tagline: "Packaging at warehouse scale",
    location: "Reno, NV · Allentown, PA",
    since: 2016,
    rating: 4.8,
    reviews: 12900,
    onTime: 99.0,
    responseHours: 1.4,
    returnRate: 0.7,
    orders: 205000,
    verified: true,
    business: true,
    netTerms: "Net 30",
    certifications: ["FSC certified", "Multi-warehouse"],
    color: "#A87B45",
  },
  {
    id: "guardline",
    name: "Guardline Safety",
    initials: "GS",
    tagline: "Certified PPE & facility supply",
    location: "Houston, TX",
    since: 2013,
    rating: 4.8,
    reviews: 26700,
    onTime: 98.7,
    responseHours: 1.0,
    returnRate: 1.1,
    orders: 388000,
    verified: true,
    business: true,
    netTerms: "Net 30 / Net 60",
    certifications: ["ANSI/ISEA", "EN 374", "ISO 45001"],
    color: "#B8A11A",
  },
];

export const sellerById = (id: string) => sellers.find((s) => s.id === id)!;
